name: Alpine

on: [push, pull_request]

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start docker
        run: |
          docker run -w /src -dit --name alpine -v $PWD:/src alpine:3.17
          echo 'docker exec alpine "$@";' > alpine-run.sh
          chmod +x alpine-run.sh

      - name: Install dependencies
        run: |
          ./alpine-run.sh apk update
          ./alpine-run.sh apk add build-base cmake g++ linux-headers git bash

      - name: Run CMake
        run: |
          ./alpine-run.sh cmake -S /src -B build -DSCN_CI=ON

      - name: Build
        run: |
          ./alpine-run.sh cmake --build build --parallel

      - name: Test
        run: |
          ./alpine-run.sh bash -c "cd build && ctest --output-on-failure"
