name: ClusterFuzzLite batch fuzzing

on:
  schedule:
    - cron: '0 0/6 * * *' # Every 6th hour
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}-${{ github.event.schedule }}
  cancel-in-progress: true

jobs:
  fuzz:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - address
          - undefined
          #- memory

    steps:
      - name: Build fuzzers
        id: build
        uses: eliaskosunen/clusterfuzzlite/actions/build_fuzzers@main
        with:
          language: c++
          sanitizer: ${{ matrix.sanitizer }}

      - name: Run fuzzers
        id: run
        uses: eliaskosunen/clusterfuzzlite/actions/run_fuzzers@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 1800
          mode: 'batch'
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true
          storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/eliaskosunen/scnlib-fuzz-corpus.git
