name: macOS

on:
  push:
    branches:
      - master
      - dev
      #- ci-*
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 12, 11 ]
        cxx: [ clang++, g++-12, g++-11, g++-10, g++-9 ]
        std: [ 17, 20 ]
        exclude:
          - os: 12
            cxx: g++-10
          - os: 12
            cxx: g++-9

    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        run: |
          locale -a
          
          mkdir ${{ runner.workspace }}/build

      - name: Run CMake
        working-directory: ${{ runner.workspace }}/build
        env:
          CXX: ${{ matrix.cxx }}
          STD: ${{ matrix.std }}
        run: |
          cmake -DSCN_CI=ON -DCMAKE_CXX_STANDARD=$STD $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --parallel

      - name: Test
        working-directory: ${{ runner.workspace }}/build
        run: ctest --output-on-failure
