name: macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        cxx: [ clang++, g++-11, g++-12 ]
        std: [ 17, 20 ]
    steps:
      - uses: action/checkout@v2

      - name: Create Build Environment
        run: mkdir ${{ runner.workspace }}/build

      - name: Run CMake
        working-directory: ${{ runner.workspace }}/build
        env:
          - CXX: ${{ matrix.cxx }}
          - STD: ${{ matrix.std }}
        run: |
          cmake -DSCN_CI=ON -DCMAKE_CXX_STANDARD=$STD $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --parallel

      - name: Test
        working-directory: ${{ runner.workspace }}/build
        run: ctest --output-on-failure
