name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, windows-2022 ]
        platform: [ Win32, x64 ]

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{ runner.workspace }}/build

      - name: Run CMake
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: |
          cmake -A ${{ matrix.platform }} $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --config Debug --parallel

      - name: Test
        working-directory: ${{ runner.workspace }}/build
        run: ctest -C Debug --output-on-failure
